<a href="https://colab.research.google.com/github/Tokhirjonov15/AI-Agent/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [8]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print("Numpy Array:", arr)

arr.shape

Numpy Array: [1 3 5 7]


(4,)

In [7]:
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print("Numpy Array2:", arr2)

arr2.shape

Numpy Array2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [10]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [11]:
# reshape()
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [12]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3.]


In [14]:
# np.zeros(), np.ones() => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 4))

print("Zeros:", z)
print("Ones:", o)

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# ndim
a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)

ndim: 2


In [19]:
# arange() making array
a = np.arange(1, 7)
print("Arange:", a)

Arange: [1 2 3 4 5 6]


In [23]:
# sum() yig'indi hisoblaydi, mean() O'rtachani hisoblaydi, max() eng kattasi, min() eng kichigi
a = np.array([1, 2, 3, 4])

print("Sum:", a.sum())
print("Mean:", a.mean())
print("Max:", a.max())
print("Min:", a.min())

Sum: 10
Mean: 2.5
Max: 4
Min: 1


In [24]:
# flatten() 2D yoki 3Dni 1Dga aylantiradi

a = np.array([[1, 2], [3, 4]])
print("Flatten:", a.flatten())

Flatten: [1 2 3 4]


In [25]:
# T (Transpose)
a = np.array([[1, 2], [3, 4]])
print("Transpose:", a.T)



Transpose: [[1 3]
 [2 4]]


In [26]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print("Dot/Multiplictaion:", a.dot(b))


Dot/Multiplictaion: [[ 4  4]
 [10  8]]


In [27]:
# random.rand()  0dan 1gacha sonlardan array yaratadi
a = np.random.rand(2, 3)
print("Random Rand:", a)

Random Rand: [[0.93026442 0.27745466 0.50891012]
 [0.69496227 0.52386836 0.51596477]]
